language: java
jdk:
  - oraclejdk8
  - oraclejdk7
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
- mvn -f code/pom.xml test -Dselenium2basics.webdriver=HTMLUNIT
- mvn -f code/pom.xml test
